name: AutoFlow Blog
title: Autoflow | AI-powered software for the automated ui testing
description: Autoflow is a software company that uses AI to automate ui testing.
tags:
  - ui testing
  - automated testing
  - ai
  - playwright
  - artificial intelligence
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: sahil@autoflowapp.com
# See: https://disqus.com/
disqus_username: https-blog-autoflow-tools
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xldrzwlw
